filter:
    excluded_paths:
        - 'tests/*'
        - 'bin/*'
        - 'docs/*'
        - 'contrib/*'

checks:
    php: true

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
# disable tests, they are horribly broken
# https://github.com/scrutinizer-ci/scrutinizer/issues/395
build:
    tests:
        override:
            command: "php -v"
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
        tests: true
